# Generated by Django 3.2.6 on 2023-07-04 15:52

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokens',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('expiration', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=255)),
                ('refresh_token_expiration', models.DateTimeField()),
            ],
            options={
                'db_table': 'access_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('polygon', models.TextField(blank=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('multipolygon', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcodes', jsonfield.fields.JSONField(blank=True, null=True)),
                ('auto_assign', models.BooleanField()),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('redirect_uri', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('expiration', models.DateTimeField()),
            ],
            options={
                'db_table': 'codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('devis', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('food', models.CharField(blank=True, max_length=255, null=True)),
                ('fragile', models.BooleanField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('order_admin', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nb_bon', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rejected_teams', jsonfield.fields.JSONField(blank=True, null=True)),
                ('pallet_is_one_entity', models.BooleanField(blank=True, null=True)),
                ('complete_to_validate', models.BooleanField(blank=True, null=True)),
                ('attribution_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coursier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('availability_not_show', models.BooleanField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coursier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultPackage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'default_package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'delivery_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispatchers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('bank_id', models.CharField(blank=True, db_column='bank_ID', max_length=255, null=True)),
                ('matriculation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dispatchers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('coordinates_extra', models.TextField()),
                ('is_moving', models.BooleanField()),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('odometer', models.FloatField()),
                ('activity', models.TextField()),
                ('battery', models.TextField()),
            ],
            options={
                'db_table': 'geolocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('locale', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hubs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', jsonfield.fields.JSONField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HubUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hub_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('validate_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_deadline', models.IntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceCourses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'invoice_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicePdfs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=1000)),
                ('loid', models.IntegerField()),
            ],
            options={
                'db_table': 'invoice_pdfs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('is_contractor', models.BooleanField(blank=True, null=True)),
                ('food', models.CharField(blank=True, max_length=255, null=True)),
                ('fragile', models.BooleanField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('matriculation', models.CharField(blank=True, max_length=255, null=True)),
                ('taxe', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_id', models.CharField(blank=True, db_column='bank_ID', max_length=255, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payment_deadline', models.IntegerField(blank=True, null=True)),
                ('created_by_admin', models.BooleanField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price_bon', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pallet_is_one_entity', models.BooleanField(blank=True, null=True)),
                ('complete_to_validate', models.BooleanField(blank=True, null=True)),
                ('is_price_visible', models.BooleanField()),
            ],
            options={
                'db_table': 'merchants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('migration_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MigrationsLock',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('is_locked', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'migrations_lock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageKinds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'package_kinds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('volumn', models.FloatField(blank=True, null=True)),
                ('fragile', models.BooleanField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('declared_value', models.FloatField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('externaldata', jsonfield.fields.JSONField(blank=True, db_column='externalData', null=True)),
            ],
            options={
                'db_table': 'packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageTypeReceiver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'package_type_receiver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('volumn', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('icon_fa', jsonfield.fields.JSONField(blank=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageTypesTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'package_types_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pallets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isadmin', models.BooleanField(blank=True, db_column='isAdmin', null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('overcost', jsonfield.fields.JSONField(blank=True, null=True)),
                ('discount', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pricing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptPdfs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=1000)),
                ('loid', models.IntegerField()),
            ],
            options={
                'db_table': 'receipt_pdfs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', jsonfield.fields.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sign', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', jsonfield.fields.JSONField(blank=True, null=True)),
                ('nb_bon', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('order_coursier', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volumn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sign_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ready_to_pick_up', models.BooleanField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('history', jsonfield.fields.JSONField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('rate_note', models.TextField(blank=True, null=True)),
                ('co2', jsonfield.fields.JSONField(blank=True, null=True)),
                ('start_interval', models.IntegerField(blank=True, null=True)),
                ('cycling', jsonfield.fields.JSONField(blank=True, null=True)),
                ('driving', jsonfield.fields.JSONField(blank=True, null=True)),
                ('altitudes', jsonfield.fields.JSONField(blank=True, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_volumn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_packages', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, db_column='team_ID', max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_rate', models.IntegerField(blank=True, null=True)),
                ('zipcode', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('renew_pwd', models.BooleanField()),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', jsonfield.fields.JSONField(blank=True, null=True)),
                ('new_user', models.BooleanField()),
                ('picture_name', models.CharField(blank=True, max_length=255, null=True)),
                ('push_token', models.TextField(blank=True, null=True)),
                ('push_os', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsGaz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('word', models.TextField(blank=True, null=True)),
                ('stdword', models.TextField(blank=True, null=True)),
                ('token', models.IntegerField(blank=True, null=True)),
                ('is_custom', models.BooleanField()),
            ],
            options={
                'db_table': 'us_gaz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsLex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('word', models.TextField(blank=True, null=True)),
                ('stdword', models.TextField(blank=True, null=True)),
                ('token', models.IntegerField(blank=True, null=True)),
                ('is_custom', models.BooleanField()),
            ],
            options={
                'db_table': 'us_lex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsRules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rule', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField()),
            ],
            options={
                'db_table': 'us_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('volumn', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonePricing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pricing', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zone_pricing',
                'managed': False,
            },
        ),
    ]
