# Generated by Django 3.2.6 on 2023-07-18 08:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonFrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal_1', models.TextField(blank=True, null=True)),
                ('geometry', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polygon_france',
                'managed': False,
            },
        ),
    ]
